Repository christoph3r3w/pleasurable-ui, pull requests merged in 2024-05, with the labels that each got.

#22 #20 client side posting
  server.js
Labels: enhancement

#30 21 bouwen algemene header voor mobile
  public/assets/close.svg
  public/assets/hamburger-menu.svg
  public/assets/images/logo.avif
  public/assets/images/logo.png
  public/assets/images/logo.webp
  public/assets/search.svg
  public/script/red.js
  public/styles/main.css
  views/partials/header.ejs
Labels: enhancement

#34 23 detail pagina layout Chris mobile-first
  public/styles/detail.css
  public/styles/main.css
  public/styles/post.css
  server.js
  views/detail.ejs
  views/partials/like.ejs
  views/partials/read-mode.ejs
  views/partials/share.ejs
  views/partials/speech.ejs
Labels: enhancement

#37 JW - Added a page loader
  public/styles/main.css
Labels: enhancement

#36 23 detail pagina layout Chris Desktop layout
  public/styles/detail.css
  views/detail.ejs
  views/partials/like.ejs
  views/partials/share.ejs
  views/partials/speech.ejs
Labels: enhancement, review

#48 JK - (re)Made time & date parser
  server.js
  views/index.ejs
Labels: enhancement

#49 JK - Added temp footer
  public/styles/main.css
  views/partials/foot.ejs
Labels: enhancement

#50 45 main header bouwen voor desktop
  public/assets/category-svgrepo-com.svg
  public/assets/theme-switch.svg
  public/script/red.js
  public/styles/header.css
  public/styles/main.css
  views/partials/head.ejs
  views/partials/header.ejs
Labels: enhancement

#51 CW additions and fixes
  public/styles/detail.css
  public/styles/header.css
  public/styles/home-page.css
  public/styles/main.css
  views/detail.ejs
Labels: enhancement

#54 JK - Changed readmore banner
  public/script/red.js
  public/styles/home-page.css
  views/index.ejs
Labels: bug

#58 53 implement darkmode for people with os preference
  public/styles/detail.css
  public/styles/header.css
  public/styles/home-page.css
  public/styles/main.css
Labels: enhancement

#57 CW header subgrid adjustments
  public/styles/header.css
  public/styles/home-page.css
Labels: enhancement, review

#56 23 detail pagina layout chris
  public/styles/detail.css
  public/styles/header.css
  views/detail.ejs
Labels: enhancement, review

#55 10 scroll driven animation detail pagina chris
  public/styles/detail.css
  views/detail.ejs
Labels: enhancement

#61 60 darkmode on os fixes
  public/styles/detail.css
  public/styles/header.css
  public/styles/home-page.css
  public/styles/main.css
Labels: enhancement

#64 CW side quest additions
  public/script/red.js
  public/styles/code-archive.css
  public/styles/detail.css
  public/styles/main.css
  views/partials/foot.ejs
Labels: enhancement

#63 62 implement theme pick function
  public/assets/logo.svg
  public/script/red.js
  public/styles/detail.css
  public/styles/header.css
  public/styles/home-page.css
  public/styles/main.css
  server.js
  views/partials/header.ejs
Labels: enhancement

#69 59 implement vpt
  package-lock.json
  package.json
  public/script/red.js
  public/styles/detail.css
  public/styles/main.css
  server.js
  views/detail.ejs
  views/index.ejs
  views/partials/head.ejs
Labels: enhancement
